### ISSUE TITLE
Remove or update Default.lua

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-102-Portrayal-Catalogue#11]
Default.lua has multiple issues:
* It won't produce any drawing instructions (because it doesn't have a case for the expected spatial type)
* It references items which aren't present in the PC:
  * DisplayPlane: `OverRadar`
  * ViewingGroup: `21010`
  * Symbol: `QUESMRK1`
  * LineStyle: `QUESMRK1`
  * ContextParameter: `PlainBoundaries`

**Comment by mikan66** [comment]
@hasel001, we haven't discussed default portrayal in the context of S-102.  We can null it out or remove it for now.  From S-101, this is for the portrayal of unknown features from the context of the portrayal engine.  XSLT does not have an equivalent rule.  I think this is the final action to resolve for S-102 version release.

**Comment by hasel001** [comment]
I infer that nulling it out won't present any major issues. I am all for that approach for this release. Thank you @mikan66 and @DavidGrant-NIWC!
