### ISSUE TITLE
Validate PC prior to release

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-102-Portrayal-Catalogue#13]
### portrayal_catalogue.xml
`styleSheets` container element is required.

**Comment by DavidGrant-NIWC** [comment]
### Lua
![image](https://github.com/user-attachments/assets/1484486c-d0a3-43ec-adb3-991b2fc32894)

### XSLT
![image](https://github.com/user-attachments/assets/3041f9dc-c920-4024-b1d0-2f502b651e82)

**Comment by mikan66** [comment]
Subtemplates are generating "no matching feature..." for XSLT.  This could probably be changes for S-102, but other products might use them too.

**Comment by DavidGrant-NIWC** [comment]
> Subtemplates are generating "no matching feature..." for XSLT. This could probably be changes for S-102, but other products might use them too.

It's not an error - we can update the validation to check for internal references.

**Comment by DavidGrant-NIWC** [comment]
After updating the validation to check for internal references:

### XSLT (no errors)
![image](https://github.com/user-attachments/assets/67eb63b3-7fe0-45dc-91be-e96d14a79684)
