### ISSUE TITLE
Remove XSLT portrayal catalog

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-102-Portrayal-Catalogue#16]
Action from S-102PT19: remove XSLT portrayal catalog

**Comment by RohdeBSH** [comment]
Hi @DavidGrant-NIWC,

The label is not correct. This change is required for S-102 ed. 3.0.0 as requested in the German comments sheet for edition 3.0.0.

**Comment by DavidGrant-NIWC** [comment]
Awaiting guidance on version number to target; see https://github.com/iho-ohi/S-102-Portrayal-Catalogue/issues/15#issuecomment-2326486882

**Comment by mikan66** [comment]
See commit [1cfd074](https://github.com/iho-ohi/S-102-Portrayal-Catalogue/commit/1cfd0748b7df11a3860afd9333baed3aed446124) for XSLT removal.
