### ISSUE TITLE
Making an Ed. 3.0.0 FC Available

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Portrayal-Catalogue#2]
One of the requirements for creating a proper Ed. 3.0.0 PC is a corresponding FC. 

In the S-102 PS repo, I've drafted an Ed. 3.0.0 FC. Because I'm unsure what namespace references need updating, I will hold off on uploading a copy to this repo. However, my draft of it can be found [here](https://github.com/iho-ohi/S-102-Product-Specification/blob/77-adaptation-of-s-100-ed-520/sources/3.0.0/FC/S-102_Ed_3.0.0_FC.xml).

Once it is correct (i.e., internally consistent, corresponding to 5.2, etc.), I will be happy to upload it here. Please let me know if it needs changes. Thanks!

**Comment by DavidGrant-NIWC** [comment]
- [x] Copied from the link provided above
- [x] Updated the namespace
- [x] Removed the schemaLocation
  * The 5.2 schemas are currently only available on the [staging server](https://staging.s100dev.net/)
  * OEM's probably don't want the online reference; they have indicated their preference is to work offline.
- [x] Replaced the existing FC supplied with the PC
  * Note: the FC is only supplied for convenience / testing. The official PC release will not contain a FC.
