### ISSUE TITLE
Update PC with xmlID values

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-102-Portrayal-Catalogue#6]
Per agreement with IHO and as done for S-101.  See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/8

![image](https://github.com/user-attachments/assets/ae78f3e7-af81-4236-b8b1-2ae32ad4e45e)

**Comment by hasel001** [comment]
I haven't updated the copy of the FC in this repo yet (I can if it won't mess with anything in progress).

In any case, the FC has been updated and can be found [here](https://drive.google.com/file/d/1WUndL21oW5YLpbSBlD5cG4eqPRkTxp9h/view?usp=drivesdk).

**Comment by mikan66** [comment]
@hasel001, your FC link to google drive is blocked on work systems.  However, the FC 3.0 version Dave updated here as main, I was able to get working with older data and the PC that is here.  It's a known good starting point before xmlID changes to the PC, (which are relatively minor).  I plan to get the xmlIDs updated today and hopefully everything working and checked in.

**Comment by mikan66** [comment]
@hasel001, Actually, I'm still working with the ORIGINAL FC (v 2.1.2).  I need to investigate migration to version FC 3.0.  The xmlIDs have been independently updated and tested against the original FC.
